### ISSUE TITLE
Self-update

### ISSUE THREAD

**Issue by hadley** [r-lib/pkg#52]
Making `pkgman::pkg_install("r-lib/pkgman")` is going to be hard, but in the short-term, we might want to special case the install so that you get something like this:

```R
pkgman::pkg_install("r-lib/pkgman")
#> Error: It's not currently possible to use pkgman to update itself
#> Instead, use devtools::install_github("r-lib/pkgman")
```

**Comment by gaborcsardi** [comment]
> Making pkgman::pkg_install("r-lib/pkgman") is going to be hard

It is actually only hard on windows, where you cannot overwrite the loaded dlls. But currently we don't have dlls, so it should be ok?

AFAICT the problem is conflicts between the dependencies of the current pkgman and the pkgman version being installed. But this is not actually specific to pkgman. It can happen to any package that has overlapping (recursive) dependencies with pkgman.
